#include "_codegen.h"

// ── Function body / declaration ────────────────────────────────────────

/**
 * Emit the body of a function: block statements, trailing result
 * expression, and an implicit `return 0;` for main.
 */
static void emit_function_body(CodeGenerator *generator, const TtNode *function_node) {
    const TtNode *body = function_node->function_declaration.body;
    const Type *return_type = function_node->function_declaration.return_type;
    bool is_unit = return_type == NULL || return_type->kind == TYPE_UNIT;
    bool is_main = strcmp(function_node->function_declaration.name, "main") == 0;

    if (body != NULL && body->kind == TT_BLOCK) {
        // Block body with optional trailing result
        codegen_emit_block_statements(generator, body);

        if (body->block.result != NULL) {
            const TtNode *result_node = body->block.result;
            // Statement-like results need special handling
            if (result_node->kind == TT_ASSIGN) {
                // Emit as statement (side-effect only in function body)
                codegen_emit_statement(generator, result_node);
            } else if (!is_unit && !is_main) {
                const char *result = codegen_emit_expression(generator, result_node);
                codegen_emit_line(generator, "return %s;", result);
            } else {
                // Unit/main: evaluate for side effects
                if (result_node->kind == TT_CALL) {
                    const char *result = codegen_emit_expression(generator, result_node);
                    codegen_emit_line(generator, "%s;", result);
                } else if (result_node->kind == TT_IF) {
                    codegen_emit_if(generator, result_node, NULL, false);
                } else {
                    const char *result = codegen_emit_expression(generator, result_node);
                    codegen_emit_line(generator, "(void)%s;", result);
                }
            }
        }
    } else if (body != NULL) {
        // Expression body (fn foo() = expr)
        const char *result = codegen_emit_expression(generator, body);
        if (!is_unit && !is_main) {
            codegen_emit_line(generator, "return %s;", result);
        } else {
            codegen_emit_line(generator, "(void)%s;", result);
        }
    }
}

/** Emit the function signature: return-type name(params). */
static void emit_function_signature(CodeGenerator *generator, const TtNode *node) {
    const char *prefix = node->function_declaration.is_public ? "" : "static ";
    const char *return_type = codegen_c_type_for(generator, node->function_declaration.return_type);
    const char *function_name = node->function_declaration.symbol->mangled_name;

    codegen_emit_indent(generator);
    fprintf(generator->output, "%s%s %s(", prefix, return_type, function_name);

    int32_t parameter_count = BUFFER_LENGTH(node->function_declaration.params);
    if (parameter_count == 0) {
        fprintf(generator->output, "void");
    } else {
        for (int32_t i = 0; i < parameter_count; i++) {
            const TtNode *parameter = node->function_declaration.params[i];
            const Type *parameter_type = parameter->parameter.param_type;
            if (parameter_type == NULL) {
                parameter_type = &TYPE_I32_INSTANCE;
            }
            if (i > 0) {
                fprintf(generator->output, ", ");
            }
            fprintf(generator->output, "%s %s", codegen_c_type_for(generator, parameter_type),
                    parameter->parameter.symbol->mangled_name);
        }
    }
}

static void emit_function_declaration(CodeGenerator *generator, const TtNode *node,
                                      bool forward_only) {
    emit_function_signature(generator, node);

    if (forward_only) {
        fprintf(generator->output, ");\n");
        return;
    }

    fprintf(generator->output, ") {\n");
    generator->indent++;
    emit_function_body(generator, node);
    generator->indent--;
    codegen_emit_line(generator, "}");
    fprintf(generator->output, "\n");
}

// ── Preamble + file emission ───────────────────────────────────────────

/** Emit the preamble: generated-file warning and required C headers. */
static void emit_preamble(CodeGenerator *generator) {
    codegen_emit(generator, "// Generated by resurg compiler - do not edit.\n");
    codegen_emit(generator, "#include <stdint.h>\n");
    codegen_emit(generator, "#include <stdbool.h>\n");
    codegen_emit(generator, "#include \"rsg_runtime.h\"\n\n");
}

/** Return true if @p node is a top-level statement. */
static bool is_top_level_statement(const TtNode *node) {
    return node->kind != TT_MODULE && node->kind != TT_FUNCTION_DECLARATION &&
           node->kind != TT_TYPE_ALIAS;
}

/**
 * Emit the auto-generated `main()` entry point that calls
 * `_rsg_top_level()`, the user's `main()`, and all zero-parameter
 * `test_*` functions.
 */
static void emit_entry_point(CodeGenerator *generator, const TtNode *file,
                             bool has_top_statements) {
    codegen_emit(generator, "int main(void) {\n");
    generator->indent++;

    if (has_top_statements) {
        codegen_emit_line(generator, "_rsg_top_level();");
    }

    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
        const TtNode *declaration = file->file.declarations[i];
        if (declaration->kind != TT_FUNCTION_DECLARATION) {
            continue;
        }
        const char *name = declaration->function_declaration.name;
        bool is_main = strcmp(name, "main") == 0;
        bool is_test = strncmp(name, "test_", 5) == 0;
        bool has_parameters = BUFFER_LENGTH(declaration->function_declaration.params) != 0;
        if ((is_main || is_test) && !has_parameters) {
            codegen_emit_line(generator, "%s();",
                              declaration->function_declaration.symbol->mangled_name);
        }
    }

    codegen_emit_line(generator, "return 0;");
    generator->indent--;
    codegen_emit(generator, "}\n");
}

/** Emit module comment and register compound types. */
static void emit_module_and_types(CodeGenerator *generator, const TtNode *file) {
    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
        const TtNode *declaration = file->file.declarations[i];
        if (declaration->kind == TT_MODULE) {
            generator->module = declaration->module.name;
            codegen_emit(generator, "// module %s\n\n", declaration->module.name);
        }
    }

    codegen_reset_compound_types(generator);
    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.compound_types); i++) {
        BUFFER_PUSH(generator->compound_types, file->file.compound_types[i]);
    }
    codegen_emit_compound_typedefs(generator);
}

/** Emit forward declarations, then full definitions, for all functions. */
static void emit_functions(CodeGenerator *generator, const TtNode *file) {
    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
        const TtNode *decl = file->file.declarations[i];
        if (decl->kind == TT_FUNCTION_DECLARATION) {
            emit_function_declaration(generator, decl, true);
        }
    }
    codegen_emit(generator, "\n");

    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
        const TtNode *decl = file->file.declarations[i];
        if (decl->kind == TT_FUNCTION_DECLARATION) {
            emit_function_declaration(generator, decl, false);
        }
    }
}

/** Emit `_rsg_top_level()` wrapper if any top-level statements exist. */
static bool emit_top_level_wrapper(CodeGenerator *generator, const TtNode *file) {
    bool has_top_statements = false;
    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
        if (is_top_level_statement(file->file.declarations[i])) {
            has_top_statements = true;
            break;
        }
    }
    if (!has_top_statements) {
        return false;
    }

    codegen_emit(generator, "static void _rsg_top_level(void) {\n");
    generator->indent++;
    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
        if (is_top_level_statement(file->file.declarations[i])) {
            codegen_emit_statement(generator, file->file.declarations[i]);
        }
    }
    generator->indent--;
    codegen_emit(generator, "}\n\n");
    return true;
}

/**
 * Emit the full C translation unit: preamble, module comment, compound
 * types, forward declarations, function definitions, and (if present)
 * a `_rsg_top_level()` wrapper for top-level statements.
 */
static void emit_file(CodeGenerator *generator, const TtNode *file) {
    emit_preamble(generator);
    emit_module_and_types(generator, file);
    emit_functions(generator, file);
    bool has_top_statements = emit_top_level_wrapper(generator, file);
    emit_entry_point(generator, file, has_top_statements);
}

// ── Public API ─────────────────────────────────────────────────────────

CodeGenerator *code_generator_create(FILE *output, Arena *arena) {
    CodeGenerator *generator = rsg_malloc(sizeof(*generator));
    generator->output = output;
    generator->arena = arena;
    generator->indent = 0;
    generator->module = NULL;
    generator->temporary_counter = 0;
    generator->string_builder_counter = 0;
    generator->compound_types = NULL;
    return generator;
}

void code_generator_destroy(CodeGenerator *generator) {
    if (generator != NULL) {
        codegen_reset_compound_types(generator);
        free(generator);
    }
}

void code_generator_emit(CodeGenerator *generator, const TtNode *file) {
    emit_file(generator, file);
}
