#include "codegen/_codegen.h"

// ── Function body / declaration ────────────────────────────────────────

/**
 * Emit the body of a function: block statements, trailing result
 * expression, and an implicit `return 0;` for main.
 */
static void emit_function_body(CodeGenerator *generator, const ASTNode *function_node) {
    const ASTNode *body = function_node->function_declaration.body;
    const Type *return_type = function_node->type;
    bool is_unit = return_type == NULL || return_type->kind == TYPE_UNIT;
    bool is_main = strcmp(function_node->function_declaration.name, "main") == 0;

    // Register parameters in variable tracking
    for (int32_t i = 0; i < BUFFER_LENGTH(function_node->function_declaration.parameters); i++) {
        const ASTNode *parameter = function_node->function_declaration.parameters[i];
        codegen_variable_define(generator, parameter->parameter.name);
    }

    if (body->kind == NODE_BLOCK) {
        // Block body with optional trailing result
        codegen_emit_block_statements(generator, body);

        if (body->block.result != NULL) {
            const ASTNode *result_node = body->block.result;
            // Statement-like results need special handling
            if (result_node->kind == NODE_ASSIGN || result_node->kind == NODE_COMPOUND_ASSIGN) {
                // Emit as statement (side-effect only in function body)
                codegen_emit_statement(generator, result_node);
            } else if (!is_unit && !is_main) {
                const char *result = codegen_emit_expression(generator, result_node);
                codegen_emit_line(generator, "return %s;", result);
            } else {
                // Unit/main: evaluate for side effects
                if (result_node->kind == NODE_CALL) {
                    const char *result = codegen_emit_expression(generator, result_node);
                    codegen_emit_line(generator, "%s;", result);
                } else if (result_node->kind == NODE_IF) {
                    codegen_emit_if(generator, result_node, NULL, false);
                } else {
                    const char *result = codegen_emit_expression(generator, result_node);
                    codegen_emit_line(generator, "(void)%s;", result);
                }
            }
        }
    } else {
        // Expression body (fn foo() = expr)
        const char *result = codegen_emit_expression(generator, body);
        if (!is_unit && !is_main) {
            codegen_emit_line(generator, "return %s;", result);
        } else {
            codegen_emit_line(generator, "(void)%s;", result);
        }
    }
}

static void emit_function_declaration(CodeGenerator *generator, const ASTNode *node, bool forward_only) {
    bool is_public = node->function_declaration.is_public;

    // Return type
    const char *return_type = codegen_c_type_for(generator, node->type);

    // Static prefix for non-public functions
    const char *prefix = !is_public ? "static " : "";

    // Mangled function name
    const char *function_name = codegen_mangle_function_name(generator, node->function_declaration.name);

    // Parameters
    codegen_emit_indent(generator);
    fprintf(generator->output, "%s%s %s(", prefix, return_type, function_name);

    int32_t parameter_count = BUFFER_LENGTH(node->function_declaration.parameters);
    if (parameter_count == 0) {
        fprintf(generator->output, "void");
    } else {
        for (int32_t i = 0; i < parameter_count; i++) {
            const ASTNode *parameter = node->function_declaration.parameters[i];
            const Type *parameter_type = parameter->type;
            if (parameter_type == NULL && parameter->parameter.type.kind == AST_TYPE_NAME) {
                parameter_type = type_from_name(parameter->parameter.type.name);
            }
            if (parameter_type == NULL) {
                parameter_type = &TYPE_I32_INSTANCE;
            }
            if (i > 0) {
                fprintf(generator->output, ", ");
            }
            fprintf(generator->output, "%s %s", codegen_c_type_for(generator, parameter_type),
                    parameter->parameter.name);
        }
    }

    if (forward_only) {
        fprintf(generator->output, ");\n");
        return;
    }

    fprintf(generator->output, ") {\n");
    generator->indent++;
    codegen_variable_scope_reset(generator);
    emit_function_body(generator, node);

    generator->indent--;
    codegen_emit_line(generator, "}");
    fprintf(generator->output, "\n");
}

// ── Preamble + file emission ───────────────────────────────────────────

/** Emit the preamble: generated-file warning and required C headers. */
static void emit_preamble(CodeGenerator *generator) {
    codegen_emit(generator, "// Generated by resurg compiler - do not edit.\n");
    codegen_emit(generator, "#include <stdint.h>\n");
    codegen_emit(generator, "#include <stdbool.h>\n");
    codegen_emit(generator, "#include \"runtime.h\"\n\n");
}

/**
 * Emit the full C translation unit: preamble, source-file constant, module
 * comment, forward declarations, function definitions, and (if present) a
 * `_rsg_top_level()` wrapper for top-level statements.
 */
static void emit_file(CodeGenerator *generator, const ASTNode *file) {
    emit_preamble(generator);

    // Emit source file path constant (used by rsg_assert)
    generator->source_file = codegen_c_escape_file_path(generator, file->location.file);
    codegen_emit(generator, "static const char *_rsg_file = \"%s\";\n\n", generator->source_file);

    // Emit module comment
    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
        const ASTNode *declaration = file->file.declarations[i];
        if (declaration->kind == NODE_MODULE) {
            generator->module = declaration->module.name;
            codegen_emit(generator, "// module %s\n\n", declaration->module.name);
        }
    }

    // Collect and emit compound type definitions (arrays, tuples)
    codegen_reset_compound_types();
    codegen_collect_compound_types(file);
    codegen_emit_compound_typedefs(generator);

    // Forward declarations for all functions
    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
        const ASTNode *declaration = file->file.declarations[i];
        if (declaration->kind == NODE_FUNCTION_DECLARATION) {
            emit_function_declaration(generator, declaration, true);
        }
    }
    codegen_emit(generator, "\n");

    // Full function definitions
    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
        const ASTNode *declaration = file->file.declarations[i];
        if (declaration->kind == NODE_FUNCTION_DECLARATION) {
            emit_function_declaration(generator, declaration, false);
        }
    }

    // Top-level statements (outside functions) — wrap in a helper if needed
    bool has_top_statements = false;
    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
        const ASTNode *declaration = file->file.declarations[i];
        if (declaration->kind != NODE_MODULE && declaration->kind != NODE_FUNCTION_DECLARATION &&
            declaration->kind != NODE_TYPE_ALIAS) {
            has_top_statements = true;
            break;
        }
    }
    if (has_top_statements) {
        codegen_emit(generator, "static void _rsg_top_level(void) {\n");
        generator->indent++;
        for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
            const ASTNode *declaration = file->file.declarations[i];
            if (declaration->kind != NODE_MODULE && declaration->kind != NODE_FUNCTION_DECLARATION &&
                declaration->kind != NODE_TYPE_ALIAS) {
                codegen_emit_statement(generator, declaration);
            }
        }
        generator->indent--;
        codegen_emit(generator, "}\n\n");
    }

    // Auto-generated entry point — calls _rsg_top_level(), user main(),
    // and all zero-parameter test_* functions.
    codegen_emit(generator, "int main(void) {\n");
    generator->indent++;

    if (has_top_statements) {
        codegen_emit_line(generator, "_rsg_top_level();");
    }

    for (int32_t i = 0; i < BUFFER_LENGTH(file->file.declarations); i++) {
        const ASTNode *declaration = file->file.declarations[i];
        if (declaration->kind != NODE_FUNCTION_DECLARATION) {
            continue;
        }
        const char *name = declaration->function_declaration.name;
        bool is_main = strcmp(name, "main") == 0;
        bool is_test = strncmp(name, "test_", 5) == 0;
        bool has_parameters = BUFFER_LENGTH(declaration->function_declaration.parameters) != 0;
        if ((is_main || is_test) && !has_parameters) {
            codegen_emit_line(generator, "%s();", codegen_mangle_function_name(generator, name));
        }
    }

    codegen_emit_line(generator, "return 0;");
    generator->indent--;
    codegen_emit(generator, "}\n");
}

// ── Public API ─────────────────────────────────────────────────────────

CodeGenerator *code_generator_create(FILE *output, Arena *arena) {
    CodeGenerator *generator = rsg_malloc(sizeof(*generator));
    generator->output = output;
    generator->arena = arena;
    generator->indent = 0;
    generator->module = NULL;
    generator->source_file = NULL;
    generator->temporary_counter = 0;
    generator->string_builder_counter = 0;
    generator->variables = NULL;
    generator->shadow_variable_counter = 0;
    return generator;
}

void code_generator_destroy(CodeGenerator *generator) {
    if (generator != NULL) {
        BUFFER_FREE(generator->variables);
        free(generator);
    }
}

void code_generator_emit(CodeGenerator *generator, const ASTNode *file) {
    emit_file(generator, file);
}
