#ifndef RSG_INTRINSIC_H
#define RSG_INTRINSIC_H

/**
 * @file intrinsic.h
 * @brief Compiler primitives — centralised registry of builtin function names
 * and their classification.
 *
 * Every compiler primitive (print, assert, panic, …) and internal
 * runtime call that requires special codegen treatment has an entry here.
 * The lower pass uses intrinsic_lookup() to dispatch; the HIR_CALL node
 * carries the IntrinsicKind so codegen can switch without strcmp.
 *
 * Primitives are low-level operations not directly exposed to users.
 * User-facing signatures live in std/builtin.rsg as decl fns;
 * the compiler auto-mangles their names and the runtime adapts.
 */

#include <stdbool.h>
#include <stdint.h>

// ── Runtime helper function names ─────────────────────────────────
// Centralised string constants to eliminate magic strings across passes.

#define RSG_FN_STR_EQUAL "rsg_str_equal"
#define RSG_FN_STR_CONCAT "rsg_str_concat"
#define RSG_FN_STR_FROM "rsg_str_from_"
#define RSG_FN_SLICE_CONCAT "rsg_slice_concat"
#define RSG_FN_ASSERT "rsg_assert"
#define RSG_FN_PANIC "rsg_panic"
#define RSG_FN_RECOVER "rsg_recover"

// ── Internal codegen naming ──────────────────────────────────────
// Prefixes for compiler-generated C identifiers.  Centralised here
// so every emit_*.c file uses the same strings.

#define RSG_INTERNAL_TMP "_rsg_tmp_"
#define RSG_INTERNAL_SB "_rsg_sb_"
#define RSG_INTERNAL_WRAP "_rsg_wrap_"
#define RSG_INTERNAL_CLEANUP "_rsg_cleanup"
#define RSG_INTERNAL_DEFER "_rsg_defer_"
#define RSG_INTERNAL_RESULT "_rsg_result"
#define RSG_INTERNAL_PANICKED "_rsg_panicked"
#define RSG_INTERNAL_PANIC_FRAME "_rsg_panic_frame"
#define RSG_INTERNAL_GC_ANCHOR "_rsg_gc_anchor"
#define RSG_INTERNAL_TOP_LEVEL "_rsg_top_level"
#define RSG_INTERNAL_TYPE_PREFIX "_Rsg"
#define RSG_INTERNAL_ENUM_PREFIX "_RsgEnum_"
#define RSG_INTERNAL_STRUCT_PREFIX "_Rsg_"

// ── Runtime ABI ──────────────────────────────────────────────────

/**
 * Runtime function name table — maps abstract operations to
 * target-specific names.
 *
 * The C backend uses the default C ABI names; a JS backend would
 * map to its own namespace (e.g. "rsg.gc.init"); WASM could map
 * to import names.
 *
 * Retrieve the default C ABI via runtime_abi_default().
 */
typedef struct {
    // GC runtime
    const char *gc_init;    // C: "rsg_gc_init"
    const char *gc_collect; // C: "rsg_gc_collect"

    // Str operations
    const char *str_new;    // C: "rsg_str_new"
    const char *str_concat; // C: "rsg_str_concat"
    const char *str_equal;  // C: "rsg_str_equal"
    const char *str_from;   // C: "rsg_str_from_" (prefix for type suffix)

    // Slice operations
    const char *slice_new;        // C: "rsg_slice_new"
    const char *slice_from_array; // C: "rsg_slice_from_array"
    const char *slice_sub;        // C: "rsg_slice_sub"
    const char *slice_concat;     // C: "rsg_slice_concat"

    // Panic/recover
    const char *panic;      // C: "rsg_panic"
    const char *recover;    // C: "rsg_recover"
    const char *assert;     // C: "rsg_assert"
    const char *panic_push; // C: "rsg_panic_push"
    const char *panic_pop;  // C: "rsg_panic_pop"

    // I/O (prefix — type suffix is appended)
    const char *print;   // C: "rsg_print_" (prefix)
    const char *println; // C: "rsg_println_" (prefix)

    // Memory
    const char *heap_alloc; // C: "rsg_heap_alloc"

    // Panic internals
    const char *is_panicking; // C: "rsg_is_panicking"
    const char *repanic;      // C: "rsg_repanic"

    // Runtime include / header
    const char *runtime_header; // C: "rsg_runtime.h"
} RuntimeABI;

/** Return the default C17 runtime ABI name table. */
const RuntimeABI *runtime_abi_default(void);

// ── Intrinsic struct field names ──────────────────────────────────

#define RSG_FIELD_LEN "len"

/** Discriminator for compiler-known primitive functions. */
typedef enum {
    INTRINSIC_NONE = 0,

    // Language primitives (detected by lower from user-facing names)
    INTRINSIC_PRINT,       // print(value)
    INTRINSIC_PRINTLN,     // println(value)
    INTRINSIC_ASSERT,      // assert(cond, msg)
    INTRINSIC_PANIC,       // panic(msg)
    INTRINSIC_CATCH_PANIC, // catch_panic(f)
    INTRINSIC_LEN,         // len(value)

    // Internal runtime calls (generated by lower, detected by codegen)
    INTRINSIC_SLICE_CONCAT, // rsg_slice_concat(a, b, sizeof(T))
} IntrinsicKind;

#define INTRINSIC_KIND_COUNT (INTRINSIC_SLICE_CONCAT + 1)

/** Metadata for a single compiler intrinsic. */
typedef struct {
    const char *name; // user-facing name (e.g. "print")
    IntrinsicKind kind;
    uint8_t min_args; // minimum arg count
    uint8_t max_args; // maximum arg count
    bool injects_loc; // auto-injects file/line (assert)
} IntrinsicDesc;

/**
 * Look up a user-facing function @p name in the intrinsic table.
 * Returns INTRINSIC_NONE if @p name is not a known intrinsic.
 */
IntrinsicKind intrinsic_lookup(const char *name);

/** Return the display name for an intrinsic kind (e.g. "print"). */
const char *intrinsic_name(IntrinsicKind kind);

/** Return the descriptor for @p kind, or NULL for INTRINSIC_NONE. */
const IntrinsicDesc *intrinsic_desc(IntrinsicKind kind);

#endif // RSG_INTRINSIC_H
