#ifndef RSG_INTRINSIC_H
#define RSG_INTRINSIC_H

/**
 * @file intrinsic.h
 * @brief Compiler primitives — centralised registry of builtin function names
 * and their classification.
 *
 * Every compiler primitive (print, assert, panic, …) and internal
 * runtime call that requires special codegen treatment has an entry here.
 * The lower pass uses intrinsic_lookup() to dispatch; the HIR_CALL node
 * carries the IntrinsicKind so codegen can switch without strcmp.
 *
 * Primitives are low-level operations not directly exposed to users.
 * User-facing signatures live in std/builtin.rsg as declare fns;
 * the compiler auto-mangles their names and the runtime adapts.
 */

#include <stdbool.h>
#include <stdint.h>

// ── Runtime helper function names ─────────────────────────────────
// Centralised string constants to eliminate magic strings across passes.

#define RSG_FN_STR_EQUAL "rsg_str_equal"
#define RSG_FN_STR_CONCAT "rsg_str_concat"
#define RSG_FN_STR_FROM "rsg_str_from_"
#define RSG_FN_SLICE_CONCAT "rsg_slice_concat"
#define RSG_FN_ASSERT "rsg_assert"
#define RSG_FN_PANIC "rsgu_panic"
#define RSG_FN_RECOVER "rsgu_recover"

// ── Intrinsic struct field names ──────────────────────────────────

#define RSG_FIELD_LEN "len"

/** Discriminator for compiler-known primitive functions. */
typedef enum {
    INTRINSIC_NONE = 0,

    // Language primitives (detected by lower from user-facing names)
    INTRINSIC_PRINT,   // print(value)
    INTRINSIC_PRINTLN, // println(value)
    INTRINSIC_ASSERT,  // assert(cond, msg?)
    INTRINSIC_PANIC,   // panic(msg)
    INTRINSIC_RECOVER, // recover()
    INTRINSIC_LEN,     // len(value)

    // Internal runtime calls (generated by lower, detected by codegen)
    INTRINSIC_SLICE_CONCAT, // rsg_slice_concat(a, b, sizeof(T))

    INTRINSIC_KIND_COUNT, // sentinel — must be last
} IntrinsicKind;

/** Metadata for a single compiler intrinsic. */
typedef struct {
    const char *name; // user-facing name (e.g. "print")
    IntrinsicKind kind;
    uint8_t min_args; // minimum arg count
    uint8_t max_args; // maximum arg count
    bool injects_loc; // auto-injects file/line (assert)
    bool is_method;   // can appear as .name() on types
} IntrinsicDesc;

/**
 * Look up a user-facing function @p name in the intrinsic table.
 * Returns INTRINSIC_NONE if @p name is not a known intrinsic.
 */
IntrinsicKind intrinsic_lookup(const char *name);

/** Return the display name for an intrinsic kind (e.g. "print"). */
const char *intrinsic_name(IntrinsicKind kind);

/** Return the descriptor for @p kind, or NULL for INTRINSIC_NONE. */
const IntrinsicDesc *intrinsic_desc(IntrinsicKind kind);

#endif // RSG_INTRINSIC_H
